### ISSUE TITLE
SELECT * statement

### ISSUE THREAD

**Issue by hector6872** [x2bool/kuery#13]
Is there any way to make a SELECT * statement?

**Comment by x2bool** [comment]
No. But this should be fairly easy to implement. I think it might be something like:
```kotlin
from(MyTable)
    .select { m -> m.all() }
```

or maybe:
```kotlin
from(MyTable)
    .selectAll()
```

**Comment by hector6872** [comment]
Just as a reminder: Maven artifact version is outdated ;)

**Comment by x2bool** [comment]
oops. Will fix that soon

**Comment by x2bool** [comment]
I have to restore my account on jCenter. It will take a few days. As a temporary workaround you could use this: https://jitpack.io/#x2bool/kuery/-SNAPSHOT

Sorry about that. I will update the main repo as soon as I can.
