### ISSUE TITLE
Failed to resolve: tel.egram.kuery:core:0.5

### ISSUE THREAD

**Issue by yaroslav-shlapak** [x2bool/kuery#18]
Environment:
IDE: Android Studio 3.2
kotlinVersion = "1.2.41"
kueryVersion = "0.5"
gradle:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
classpath 'com.android.tools.build:gradle:3.2.0-alpha16'

Description:
Adding 
// Core library
implementation "tel.egram.kuery:core:$kueryVersion"
// SQLite dialect
implementation "tel.egram.kuery:sqlite:$kueryVersion"
to the main module gradle file leads to gradle build error:
Failed to resolve: tel.egram.kuery:core:0.5

**Comment by x2bool** [comment]
Do you have jCenter configured?

**Comment by yaroslav-shlapak** [comment]
jCenter seems to be configured. Or have I missed something?
Root gradle file:
```
buildscript {
    apply from: "$rootDir/versions.gradle"
    repositories {
        mavenCentral()
        jcenter()
        google()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0-alpha16'
        classpath 'com.google.gms:google-services:3.2.1'
        //noinspection GradleDynamicVersion
        classpath 'io.fabric.tools:gradle:1.+'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

allprojects {
    repositories {
        jcenter()
        google()
        mavenCentral()
    }
    apply from: "$rootDir/versions.gradle"
}
```

**Comment by x2bool** [comment]
Looks right. I will check package.

**Comment by x2bool** [comment]
Yep! 0.5 for some reason isn't resolved properly. I created a ticket at Bintray. Let's see how it goes. Thank you for reporting this.

**Comment by x2bool** [comment]
Hi! I had to restore ownership on the jcenter repo, but everything should work now. Feel free to reopen issue if something doesn't work.

**Comment by yaroslav-shlapak** [comment]
Seems to work now, thank you!
